version: '3.9'

services:
  app-apache:
    build:
      context: .
      dockerfile: Dockerfile-apache
    restart: always
#    ports:
#        - "8000:80"         # This is for apache
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-apache.rule=Host(`test-laravel-apache.local`)"
      - "traefik.http.services.app-apache.loadbalancer.server.port=80"
    volumes:
      - .:/var/www/html    # This is for apache

networks:
    test-network:
        external: true
